### ISSUE TITLE
launch crash on my modpack, not sure why.

### ISSUE THREAD

**Issue by netcore10** [JSJBDEV/ACE#3]
[crash-2022-05-26_20.36.06-client.txt](https://github.com/JSJBDEV/ACE/files/8781632/crash-2022-05-26_20.36.06-client.txt)

**Comment by JSJBDEV** [comment]
this looks like something to do with computercraft, rather than ACE apart from the mods list it is not listed as erroring

**Comment by netcore10** [comment]
Oh dang. I wonder why computer craft messes with ace?

**Comment by JSJBDEV** [comment]
I think your problem might rely in another mod interaction, I don't see ace in any of errors in that log. You probably want to report it to the computer craft people, unless they told you to come here?

**Comment by netcore10** [comment]
I'll report to them
