### ISSUE TITLE
Some spells crash servers, Evil Mages cast these spells randomly

### ISSUE THREAD

**Issue by FatherSarge** [JSJBDEV/ACE#4]
Certain spells like Earth Launch(probably others) cause servers to crash. Evil Mages can use these spells randomly and can soft lock servers and hard lock single player games.

Please also provide a config file so if issues like this happen again Evil Mages' spell list and spawn rate (disable spawn mostly) can be altered by the user.

For anyone having this issue, the best way to currently solve it is to install Carpet mod on your server, use the /tick freeze command from your console (this stops all game activity entirely while letting you move around the world, place blocks, etc)

You can then login to use the command /kill @e[type=ace:evil_mage] command. I suggest setting this up in a command block with an observer clock to instakill mages until this bug is fixed. Which I hope is speedy and at least for 1.18.2.

If you are on single player, not sure you can save your world. Maybe changing to peaceful in the files.

**Comment by JSJBDEV** [comment]
I thought I fixed all of those, but I was working on the fork RACE4ACE, not sure I ever built it however. If I get time, I will see what still needs to fix. please provide crashlogs.

**Comment by JSJBDEV** [comment]
also try 0.6 just released on modrinth

**Comment by zauberparacelsus** [comment]
this issue appears to still be happening on 0.7.1
